[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["Rich Churcher <rich.churcher@gmail.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.2.2"
aoc-runner-derive = "0.2.2"
array_tool = "1.0.3"
itertools = "0.8.2"

